### ISSUE TITLE
NXP i.MX RT10xx series IBIS import pin arrangement

### ISSUE THREAD

**Issue by FPSUsername** [issus/CelestialPinArranger#2]
Upon importing the IBIS file for the [RT1050](https://www.nxp.com/products/processors-and-microcontrollers/arm-microcontrollers/i-mx-rt-crossover-mcus/i-mx-rt1050-crossover-mcu-with-arm-cortex-m7-core:i.MX-RT1050?fpsp=1&tab=Design_Tools_Tab) series MCU chip, the pin arranger only creates one large part. ([Direct link](https://www.nxp.com/downloads/en/ibis-model/rt1050_bga12x12_0.8pitch.ibs))
![image](https://user-images.githubusercontent.com/10143926/157050643-72ef9506-deb8-459f-ae36-995f606630de.png)

I believe that creating a better arrangement for this IBIS file will also solve the arrangement on any RT10xx series IBIS file.

**Comment by issus** [comment]
Working pretty well now for the files I tested. For any NXP mcu you've better off using the signal_configuration.xml for the exact MCU model downloaded from: https://mcuxpresso.nxp.com/en/select_config_tools_data#

**Comment by FPSUsername** [comment]
It seems that for a family of MCU models, the `signal_configuration.xml` is shared between multiple models. For example, the `RT1051xxxxB` and `RT1052xxxxB` each has four models.
If you open the `signal_configuration.xml` from a model that links to another XML file, the pin arranger throws an arranger error:
![image](https://user-images.githubusercontent.com/10143926/161279928-f72b5109-f04b-429a-bc44-85dfa6ea95ae.png)

Assuming that the user extracts the whole archive, it would be possible to let the pin arranger find the reference file:
```xml
<!-- MIMXRT1052DVJ6B/signal_configuration.xml -->
...
<reference file="MIMXRT1052CVJ5B/signal_configuration.xml"/>
...
```

As the folder structure would be as:
- processors
  - MIMXRT1052xxxxB
    - ksdk2_0
      - MIMXRT1052CVJ5B
        - signal_configuration.xml
      - MIMXRT1052CVL5B
        - signal_configuration.xml
      - MIMXRT1052CVJ6B
        - signal_configuration.xml
      - MIMXRT1052CVL6B
        - signal_configuration.xml
