### ISSUE TITLE
Pin name is being limited [STM]

### ISSUE THREAD

**Issue by FPSUsername** [issus/CelestialPinArranger#4]
When creating a symbol using the STM32Cube XML file, it can sometimes happen that the pin name is shortened to the first underscore.

Example of the STM32F407V(E-G)Tx:
```XML
    <Pin Name="PB12" Position="51" Type="I/O">
        <Signal Name="CAN2_RX"/>
        <Signal Name="ETH_TXD0"/>
        <Signal Name="I2C2_SMBA"/>
        <Signal Name="I2S2_WS"/>
        <Signal Name="SPI2_NSS"/>
        <Signal Name="TIM1_BKIN"/>
        <Signal Name="USART3_CK"/>
        <Signal Name="USB_OTG_HS_ID"/>
        <Signal Name="USB_OTG_HS_ULPI_D5"/>
        <Signal IOModes="Input,Output,Analog,EVENTOUT,EXTI" Name="GPIO"/>
    </Pin>
```

Where the pin output is:
`PB12/CAN2/ETH/I2C2/I2S2/SPI2/TIM1/USART3/USB`

I believe this to be due to pin name length limitation, but I am not sure if that's the case.

**Comment by issus** [comment]
This is working as intended. When a pin's name gets too long, the specific feature of a peripheral is trimmed. This still gives you guidance that the pin has that peripheral available on the pin, even if the feature is cut.
